name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        echo 'Building...'
        docker build -t website:latest .
        echo 'Build completed.'

  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      run: |
        echo 'Deploying...'
        docker run website:latest
        echo 'Deploy complete.'
