name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: build
      env: 
        GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}
      run: |
        echo 'Building...'
        docker build -t website:latest --build-arg GH_PASS_ARG=$GITHUB_PASSWORD .
        echo 'Build completed.'
    - name: deploy
      run: |
        echo 'Deploying...'
        docker run website:latest
        echo 'Deploy complete.'
        
